# TalesZ Plugin
#§
name: TalesZ
version: 1.5.1
author: MoKunz
main: com.talesdev.talesz.TalesZ
depend: [ProtocolLib,WorldEdit]
softdepend: [WorldGuard]
commands:
    xputil:
        description: "Commands of Xp System module"
        usage: "Usage : /xptest <operation> <args>"
        permission: talesz.command.xputil
        permission-message: "§cYou don't have permission to use this command."
    bleeding:
        description: "Commands of Bleeding System module"
        usage: "Usage : /bleeding <operation> <args>"
        permission: talesz.command.bleeding
        permission-message: "§cYou don't have permission to use this command."
    talesz:
        description: "TalesZ(MineZ) - A multiplayer zombie survival plugin system.\nAuthor : MoKunz (talesdev.com)"
        usage: "/talesz <subcommand> <args>"
        permission: talesz.command.talesz
        permission-message: "§cYou don't have permission to use this command."
    taleszitem:
        description: "TalesZ(MineZ) Item System"
        usage: "Usage : /taleszitem <operation> <args>"
        permission: talesz.command.taleszitem
        permission-message: "§cYou don't have permission to use this command."
    taleszspawn:
        description: "TalesZ World command"
        usage: "/taleszspawn - Warp you to random spawn location of TalesZ World"
        permission: talesz.commmand.taleszspawn
        permission-message: "§cYou don't have permission to use this commnd."
permissions:
    talesz.*:
        description: "Give you access to all function of TalesZ"
        default: op
        children:
            talesz.command.*:
                description: "Give you access to all command of TalesZ"
                default: op
                children:
                    talesz.command.xputil:
                        description: "Give you access to /xputil command"
                        default: false
                    talesz.command.bleeding:
                        description: "Give you access to /xputil command"
                        default: false
                    talesz.command.talesz:
                        description: "Give you access to /xputil command"
                        default: false
                    talesz.command.taleszitem:
                        description: "Give you access to /xputil command"
                        default: false
                    talesz.command.taleszspawn:
                        description: "Give you access to /xputil command"
                        default: true