#§
name: TalesZ
version: 1.2
author: MoKunz
main: com.talesdev.talesz.Main
depend: [ProtocolLib]
softdepend: [WorldGuard]
commands:
    xputil:
        description: "Commands of Xp System module"
        usage: "Usage : /xptest <operation> <args>"
        permission: talesz.command.xputil
        permission-message: "§4You don't have permission to use this command."
    bleeding:
        description: "Commands of Bleeding System module"
        usage: "Usage : /bleeding <operation> <args>"
        permission: talesz.command.bleeding
        permission-message: "§4You don't have permission to use this command."
    talesz:
        description: "TalesZ(MineZ) - A multiplayer zombie survival plugin system.\nAuthor : MoKunz (talesdev.com)"
        usage: "/talesz spawnItem <player> <itemName>"
        permission: talesz.command.talesz
        permission-message: "§4You don't have permission to use this command."
    taleszitem:
        description: "TalesZ(MineZ) Item System"
        usage: "Usage : /taleszitem <operation> <args>"
        permission: talesz.command.taleszitem
        permission-message: "§4You don't have permission to use this command."
